// Writes every logo file the site serves from the one geometry source (nsn-logo.mjs).
//   node brand/build.mjs          write the SVGs and web/src/lib/logo.ts
//   node brand/build.mjs --check  exit 1 if any of them is out of date
// PNG and ICO files come from brand/raster.mjs (needs a browser; run it only when the geometry changes).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { INK, GREEN, markSvg, horizontal, tile } from './nsn-logo.mjs';

const root = new URL('../', import.meta.url);
const ACCENT = 'var(--logo-accent, currentColor)'; // inline logo: nut and letters follow text colour, needle follows the accent
const parts = (svg) => {
  const m = svg.match(/^<svg [^>]*viewBox="([^"]+)"[^>]*>(.*)<\/svg>$/s);
  const [, , w, h] = m[1].split(' ').map(Number);
  return { viewBox: m[1], w, h, body: m[2] };
};
const banner = '<!-- Generated by brand/build.mjs from brand/nsn-logo.mjs. Do not edit by hand. -->\n';
const lockup = parts(horizontal({ needle: ACCENT, small: true }).svg);
const mark = parts(markSvg({ needle: ACCENT, small: true }));

export const files = {
  'web/public/favicon.svg': banner + tile({ size: 32, small: true, fillRatio: 0.84 }) + '\n',
  'web/public/mark.svg': banner + markSvg({ nut: INK, needle: GREEN }) + '\n',
  'web/public/logo.svg': banner + horizontal({ nut: INK, needle: GREEN, word: INK }).svg + '\n',
  'web/src/lib/logo.ts':
    '// Generated by brand/build.mjs from brand/nsn-logo.mjs. Do not edit by hand.\n' +
    '// Inline logo for the Logo component. Small-size cut of the mark: the header and footer sit under 48 px.\n' +
    'export interface LogoArt { viewBox: string; w: number; h: number; body: string }\n' +
    `export const LOCKUP: LogoArt = ${JSON.stringify(lockup)};\n` +
    `export const MARK: LogoArt = ${JSON.stringify(mark)};\n`,
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [rel, text] of Object.entries(files)) {
    const p = fileURLToPath(new URL(rel, root));
    if (check) {
      if (!existsSync(p) || readFileSync(p, 'utf8') !== text) { console.error('out of date: ' + rel); stale++; }
    } else { writeFileSync(p, text); console.log('wrote ' + rel); }
  }
  if (check) { if (stale) process.exit(1); console.log('logo files match brand/nsn-logo.mjs'); }
}
